modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "survivalisland"
version = "${version}"
displayName = "Survival Island"
authors = "jaskarth"
description = '''
A configurable island generator!
'''
#logoFile = "icon.png"

[[mixins]]
config = "survivalisland.mixins.json"

[[dependencies.survivalisland]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.survivalisland]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"
